// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindbellTank.Models;

#nullable disable

namespace WindbellTank.Migrations
{
    [DbContext(typeof(WindbellDbContext))]
    [Migration("20260423084130_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WindbellTank.Models.DensitySetting", b =>
                {
                    b.Property<string>("TankNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DensityFloatNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FixRate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HeightDiff")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InitDensity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecondDensity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("TankNo");

                    b.ToTable("WindbellDensitySettings", (string)null);
                });

            modelBuilder.Entity("WindbellTank.Models.GasSensorSetting", b =>
                {
                    b.Property<string>("SensorNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PositionNum")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("SensorNo");

                    b.ToTable("WindbellGasSensorSettings", (string)null);
                });

            modelBuilder.Entity("WindbellTank.Models.OilProductSetting", b =>
                {
                    b.Property<string>("OilCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ExpansionRate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OilColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OilName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WeightDensity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("OilCode");

                    b.ToTable("WindbellOilProductSettings", (string)null);
                });

            modelBuilder.Entity("WindbellTank.Models.ProbeSetting", b =>
                {
                    b.Property<string>("TankNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProbeId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("HighAlarmMm")
                        .HasColumnType("float");

                    b.Property<double>("HighTempC")
                        .HasColumnType("float");

                    b.Property<double>("HighWarningMm")
                        .HasColumnType("float");

                    b.Property<bool>("IsDensityProbe")
                        .HasColumnType("bit");

                    b.Property<double>("LowAlarmMm")
                        .HasColumnType("float");

                    b.Property<double>("LowTempC")
                        .HasColumnType("float");

                    b.Property<double>("LowWarningMm")
                        .HasColumnType("float");

                    b.Property<double>("OilBlindMm")
                        .HasColumnType("float");

                    b.Property<double>("OilOffsetMm")
                        .HasColumnType("float");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("WaterAlarmMm")
                        .HasColumnType("float");

                    b.Property<double>("WaterOffsetMm")
                        .HasColumnType("float");

                    b.Property<double>("WaterWarningMm")
                        .HasColumnType("float");

                    b.HasKey("TankNo", "ProbeId");

                    b.ToTable("WindbellProbeSettings", (string)null);
                });

            modelBuilder.Entity("WindbellTank.Models.SensorSetting", b =>
                {
                    b.Property<string>("SensorNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PositionNum")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("SensorNo");

                    b.ToTable("WindbellSensorSettings", (string)null);
                });

            modelBuilder.Entity("WindbellTank.Models.SystemVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DensityVer")
                        .HasColumnType("int");

                    b.Property<int>("GasVer")
                        .HasColumnType("int");

                    b.Property<int>("OilProductVer")
                        .HasColumnType("int");

                    b.Property<int>("ProbeVer")
                        .HasColumnType("int");

                    b.Property<int>("SensorVer")
                        .HasColumnType("int");

                    b.Property<int>("TableVer")
                        .HasColumnType("int");

                    b.Property<int>("TankVer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WindbellSystemVersions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DensityVer = 1,
                            GasVer = 1,
                            OilProductVer = 1,
                            ProbeVer = 1,
                            SensorVer = 1,
                            TableVer = 1,
                            TankVer = 1
                        });
                });

            modelBuilder.Entity("WindbellTank.Models.TankSetting", b =>
                {
                    b.Property<string>("TankNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DiameterMm")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("ExpansionRate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OilCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OilName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("VolumeLiters")
                        .HasColumnType("int");

                    b.HasKey("TankNo");

                    b.ToTable("WindbellTankSettings", (string)null);
                });

            modelBuilder.Entity("WindbellTank.Models.TankTableEntry", b =>
                {
                    b.Property<string>("TankNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("HeightMm")
                        .HasColumnType("int");

                    b.Property<int>("VolumeLiters")
                        .HasColumnType("int");

                    b.HasKey("TankNo", "HeightMm");

                    b.ToTable("WindbellTankTableEntries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
